import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/store/provider/store-provider";
import Stack from "@mui/material/Stack";
import AppHeader from "@/components/header";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Stack>
            <AppHeader />
            <Container component={'main'} maxWidth="lg">
              {children}
            </Container>
          </Stack>
        </StoreProvider>
      </body>
    </html>
  );
}
